language: node_js
node_js: lts/*
jobs:
  include:
    - stage:
      before_script: npm run lint
      script:
        - npm run lint
        - npm t
      deploy:
        provider: npm
        email: $NPM_USER
        api_key: $NPM_AUTH_KEY
        on:
          branch: master
          tags: true
      after_success: echo "Genial!"
      after_failure: echo "Oooh!"
