language: node_js
node_js: lts/*
jobs:
  include:
    - stage:
      before_script: npm run lint
      script:
        - npm run lint
        - npm t
        - npm run coveralls
      deploy:
        provider: npm
        email: $NPM_USER
        api_key: $NPM_AUTH_KEY
        on:
          tags: true
