module.exports = {
  SERVER_STARTED: "ServerEvent / STARTED",
  SERVER_SOCKET_MESSAGE: "ServerEvent / SOCKET MESSAGE",
  SERVER_FORCE_FINISH: "ServerEvent / FORCE FINISH",
  SERVER_SOCKET_CLOSED: "ServerEvent / SOCKET CLOSED",
  SERVER_FEATURES_CHANGED: "ServerEvent / FEATURES CHANGED",
  SERVER_FILES_CHANGED: "ServerEvent / FILES CHANGED",
  SERVER_MANAGER_UPDATED: "MANAGER_UPDATED"
};
